### ISSUE TITLE
Ukjent feil MQTT

### ISSUE THREAD

**Issue by knutmyr** [toreamun/amshan-homeassistant#29]
## Configuration

```yaml

Add your logs here.

```

## Describe the bug
Hei
Prøver legge inn MQTT topic, men den bare timer ut med  unknown error,
Er det fordi det er passord på mqtt, eller er det en annen grunn?

## Debug log

```text

Add your logs here.

```

**Comment by toreamun** [comment]
Dette vil kunne skje om den ikke mottar noen meldinger eller ikke mottar noen meldinger som den klarer å dekode. Ved bruk av MQTT vil det kunne være at topic er feil. Hvis topic er riktig men den ikke klarer å dekode meldingene er det veldig fint om du kan poste meldingene her slik at feilen kan rettes. Se hvordan lenger nede.

Integrasjonen benytter [MQTT integrasjonen i Home Assistant](https://www.home-assistant.io/integrations/mqtt/). Hvis du benytter passord for MQTT, så er det under konfigurasjonen av MQTT i Home Assistant du legger inn passordet.

Hvis du går til konfigurasjonen av MQTT i Home Assistant (http://homeassistant.local:8123/config/mqtt eller Configuration -> Integrations -> MQTT -> Configure) så er det mulig å se hva som blir sendt til MQTT. Her kan du skrive inn topic du forsøkte for integrasjonen og se om noe og hva som blir mottatt.

Et annet alternativ er å sette endre loglevel til debug for integrasjonen (custom_components.amshan: debug). Se mer om hvordan her: https://www.home-assistant.io/integrations/logger/
Jeg tror endring av log level i configuration.yaml krever restart av Home Assistant. Loggen finner man i filsystemet eller ved å gå til http://homeassistant.local:8123/config/logs og klikke på knappen "Load full Home Assistant log" helt nederst.

**Comment by toreamun** [comment]
Benytter du Mosquitto broker Add on? Jeg fikk et tips nå om at det kommet en oppdatering v6 som har noen endringer som potensielt kan gi problemer. Blant annet krav om brukernavn/passord og autentisering med HASS.  I dokumentasjonen for addon står det nå "If you have old MQTT settings available, remove this old integration and restart Home Assistant to see the new one.". Men det sies at dette ikke alltid løser problemet.

**Comment by knutmyr** [comment]
Ser ut som ett av problemene er at amstomqttbridge ikke publiserer raw til mqtt som den skal. Må velge json for at den skal publisere noe som helst.
Tenker jeg kjører inn en esphome serial og tester den etter jobb i dag

**Comment by toreamun** [comment]
> Ser ut som ett av problemene er at amstomqttbridge ikke publiserer raw til mqtt som den skal. Må velge json for at den skal publisere noe som helst. 

Det forklarer saken. https://github.com/gskjold/AmsToMqttBridge har planlagt støtte for å videresende de nødvendige "rå" meldinger fra måleren **fra versjon 2.1**. I [planen](https://github.com/gskjold/AmsToMqttBridge/milestone/22?closed=1) står [oppgaven](https://github.com/gskjold/AmsToMqttBridge/issues/210) som lukket allerede, så dette går nok som planlagt.

**Comment by aTommyC** [comment]
Har lignende utfordring, men med Mosquitto og AMSHAN og Tibber Pulse. Problemet oppsto som Tore beskriver, etter en oppdatering. Uten at jeg nileste release notes, ser jeg at det kom en vesentlig endring ift anonymous i v6 av addon. 

Gjør noen tester, og kommer tilbake.

**Comment by toreamun** [comment]
Det slår meg at hvis Mosquitto Addon nå ikke lenger tillater anonym publisering (v6: Support for anonymous logins has been removed), så vil ikke "standard oppskriften" https://github.com/iotux/ElWiz#oppsett-av-pulse fungere. Pulse har såvidt jeg vet ingen mulighet til å legge inn brukernavn og passord, men støtter sertifikat uten at jeg nå vet om Mosquitto Addon gjør det.

Denne endringen om å ikke tillate anonyme logins tipper jeg vil gi utfordringer på kort sikt for mange andre integrasjoner også. Det hadde vært greit å ha en av/på bryter for det kravet...

**Comment by dioden55** [comment]
Hei
Jeg har prøvd å få igang dette tillegget i dag.
Bruker ams reader og  har satt den til å sende "RAW" i mqtt opsettet.
Når jeg prøver å starte integrasjonen får jeg timeout reading ...
Har sjekket i log, der får jeg : 

2022-02-18 13:07:36 DEBUG (MainThread) [custom_components.amshan.metercon] Ignore JSON in payload without HDLC framing from topic power/meter/import/active/accumulated: 77443.648
2022-02-18 13:07:38 DEBUG (MainThread) [custom_components.amshan.metercon] Ignore JSON in payload without HDLC framing from topic power/meter/import/active: 2586
2022-02-18 13:07:41 DEBUG (MainThread) [custom_components.amshan.metercon] Ignore JSON in payload without HDLC framing from topic power/meter/l1/current: 10.7
2022-02-18 13:07:41 DEBUG (MainThread) [custom_components.amshan.metercon] Ignore JSON in payload without HDLC framing from topic power/meter/l1/voltage: 241.8
2022-02-18 13:07:41 DEBUG (MainThread) [custom_components.amshan.metercon] Ignore JSON in payload without HDLC framing from topic power/meter/import/active: 2582.

Nar også testet med å sette mqtt til jason i amsreader, da får jeg : 


2022-02-18 13:21:08 DEBUG (MainThread) [custom_components.amshan.metercon] Ignore JSON in payload without HDLC framing from topic power: {'id': '44:17:93:24:F9:42', 'name': 'amsreader', 'up': 9953, 't': 0, 'vcc': 3.311, 'rssi': -68, 'temp': -127.0, 'data': {'P': 1574}}
2022-02-18 13:21:11 DEBUG (MainThread) [custom_components.amshan.metercon] Ignore JSON in payload without HDLC framing from topic power: {'id': '44:17:93:24:F9:42', 'name': 'amsreader', 'up': 9956, 't': 0, 'vcc': 3.294, 'rssi': -68, 'temp': -127.0, 'data': {'lv': 'AIDON_V0001', 'id': '7359992897114385', 'type': '6515', 'P': 1586, 'Q': 38, 'PO': 0, 'QO': 0, 'I1': 6.6, 'I2': 0.0, 'I3': 0.0, 'U1': 240.4, 'U2': 0.0, 'U3': 0.0}}
2022-02-18 13:21:13 DEBUG (MainThread) [custom_components.amshan.metercon] Ignore JSON in payload without HDLC framing from topic power: {'id': '44:17:93:24:F9:42', 'name': 'amsreader', 'up': 9958, 't': 0, 'vcc': 3.311, 'rssi': -68, 'temp': -127.0, 'data': {'P': 1586}}

Kan dere s hva som feiler ?

**Comment by dioden55** [comment]
> > Bruker ams reader og  har satt den til å sende "RAW" i mqtt opsettet.
> 
> Med ams reader, mener du da https://github.com/gskjold/AmsToMqttBridge? Det forklarer i så fall saken. https://github.com/gskjold/AmsToMqttBridge har planlagt støtte for å videresende de nødvendige "rå" meldinger fra måleren fra versjon 2.1. I [planen](https://github.com/gskjold/AmsToMqttBridge/milestone/22?closed=1) står [gskjold/AmsToMqttBridge#210](https://github.com/gskjold/AmsToMqttBridge/issues/210) som lukket allerede, så dette går nok som planlagt.
> 
> Det som heter [raw](https://github.com/gskjold/AmsToMqttBridge/wiki/MQTT-configuration#topics-in-raw-mode) nå i gjeldende public release er etter min mening ikke så veldig "raw". Jeg er spent på hva de kaller formatet for rådata fra måler når release 2.1 er klar.

Takk for raskt svar. Da er det bare å vente på ny firmware. :)

**Comment by sesthan** [comment]
Kan jag ta den här tråd lite :)
Har  fel "Timeout reading data" när jag forsöker med topic "esp32_C5170C/raw"

Jag har en energyintelligence.se P1 + Kamstrup Omipower. Mitt elborlag har set till att min Kamstrup sickar via P1 standard jag ser data i energyintelligence.se webinterfacet. 

I HASS kan jag subscripe till topic och få ibland ett raw meddelat -->
![image](https://user-images.githubusercontent.com/31334971/160007511-5cfdd70f-cd99-48ba-9de2-2cf95f1a3014.png)

samma om jag subscriper på min windows maskin via MQTT Explorer
![image](https://user-images.githubusercontent.com/31334971/160008213-db75f1f9-410c-4925-9637-9ddeedaceb6b.png)

Info om energyintelligence.se P1
![image](https://user-images.githubusercontent.com/31334971/160008054-b58c1751-34b1-4087-bb7d-cb1d6e0cc638.png)


Extra info FYI:
MQTT broker som kör på en docker på min server. Min hass kör i egen VM med egen nätverk, för att verifiera MQTT har jag andra docker som sicker MQTT meddelat till HASS, och det funkar fint. 


**Lite oklart om MQTT har rätt format?**

**Comment by toreamun** [comment]
Har du mulighet til å hente ut loggen? Se https://github.com/toreamun/amshan-homeassistant/wiki/Feils%C3%B8king

**Comment by sesthan** [comment]
> Har du mulighet til å hente ut loggen? Se https://github.com/toreamun/amshan-homeassistant/wiki/Feils%C3%B8king

Yes, fick städa lite för ickerelevant kanske känslig info.. Men här -->
[home-assistant.log](https://github.com/toreamun/amshan-homeassistant/files/8349115/home-assistant.log)

Hittat interssant information kring "payload without HDLC framing" och " Starts with '/', but not a valid P1 message: Data not found." kanske det är en förklaring? 
`
2022-03-25 09:06:10 DEBUG (MainThread) [custom_components.amshan.metercon] Got payload without HDLC framing from topic esp32_C5170C/raw: 370d002f4b414d350d000d00302d303a312e302e302832323033323530393036303957290d00312d303a312e382e302830303036303237322e3933332a6b5768290d00312d303a322e382e302830303030303030302e3030302a6b5768290d00312d303a332e382e302830303030303031322e3639302a6b56417268290d00312d303a342e382e302830303031323337312e3330372a6b56417268290d00312d303a312e372e3028303030312e3031302a6b57290d00312d303a322e372e3028303030302e3030302a6b57290d00312d303a332e372e3028303030302e3030302a6b564172290d00312d303a342e372e3028303030302e3630302a6b564172290d00312d303a32312e372e3028303030302e3733312a6b57290d00312d303a34312e372e3028303030302e3039372a6b57290d00312d303a36312e372e3028303030302e3138322a6b57290d00312d303a32322e372e3028303030302e3030302a6b57290d00312d303a34322e372e3028303030302e3030302a6b57290d00312d303a36322e372e3028303030302e3030302a6b57290d00312d303a32332e372e3028303030302e3030302a6b564172290d00312d303a34332e372e3028303030302e3030302a6b564172290d00312d303a36332e372e3028303030302e3030302a6b564172290d00312d303a32342e372e3028303030302e3233392a6b564172290d00312d303a34342e372e3028303030302e3134342a6b564172290d00312d303a36342e372e3028303030302e3231372a6b564172290d00312d303a33322e372e30283233372e352a56290d00312d303a35322e372e30283234312e312a56290d00312d303a37322e372e30283234322e342a56290d00312d303a33312e372e30283030332e332a41290d00312d303a35312e372e30283030302e372a41290d00312d303a37312e372e30283030312e332a41290d0021363539350d00
2022-03-25 09:06:20 DEBUG (MainThread) [custom_components.amshan.metercon] Starts with '/', but not a valid P1 message: Data not found.
2022-03-25 09:06:20 DEBUG (MainThread) [custom_components.amshan.metercon] Got payload without HDLC framing from topic esp32_C5170C/raw: 2f4b414d350d000d00302d303a312e302e302832323033323530393036313957290d00312d303a312e382e302830303036303237322e3933362a6b5768290d00312d303a322e382e302830303030303030302e3030302a6b5768290d00312d303a332e382e302830303030303031322e3639302a6b56417268290d00312d303a342e382e302830303031323337312e3330392a6b56417268290d00312d303a312e372e3028303030312e3030352a6b57290d00312d303a322e372e3028303030302e3030302a6b57290d00312d303a332e372e3028303030302e3030302a6b564172290d00312d303a342e372e3028303030302e3539392a6b564172290d00312d303a32312e372e3028303030302e3733312a6b57290d00312d303a34312e372e3028303030302e3039372a6b57290d00312d303a36312e372e3028303030302e3137372a6b57290d00312d303a32322e372e3028303030302e3030302a6b57290d00312d303a34322e372e3028303030302e3030302a6b57290d00312d303a36322e372e3028303030302e3030302a6b57290d00312d303a32332e372e3028303030302e3030302a6b564172290d00312d303a34332e372e3028303030302e3030302a6b564172290d00312d303a36332e372e3028303030302e3030302a6b564172290d00312d303a32342e372e3028303030302e3233392a6b564172290d00312d303a34342e372e3028303030302e3134342a6b564172290d00312d303a36342e372e3028303030302e3231362a6b564172290d00312d303a33322e372e30283233372e322a56290d00312d303a35322e372e30283234302e382a56290d00312d303a37322e372e30283234322e322a56290d00312d303a33312e372e30283030332e332a41290d00312d303a35312e372e30283030302e372a41290d00312d303a37312e372e30283030312e332a41290d0021314233300d
2022-03-25 09:06:30 DEBUG (MainThread) [custom_components.amshan.metercon] Got payload without HDLC framing from topic esp32_C5170C/raw: 0a2f4b414d350d000d00302d303a312e302e302832323033323530393036323957290d00312d303a312e382e302830303036303237322e3933392a6b5768290d00312d303a322e382e302830303030303030302e3030302a6b5768290d00312d303a332e382e302830303030303031322e3639302a6b56417268290d00312d303a342e382e302830303031323337312e3331312a6b56417268290d00312d303a312e372e3028303030312e3030372a6b57290d00312d303a322e372e3028303030302e3030302a6b57290d00312d303a332e372e3028303030302e3030302a6b564172290d00312d303a342e372e3028303030302e3539362a6b564172290d00312d303a32312e372e3028303030302e3733312a6b57290d00312d303a34312e372e3028303030302e3039372a6b57290d00312d303a36312e372e3028303030302e3137392a6b57290d00312d303a32322e372e3028303030302e3030302a6b57290d00312d303a34322e372e3028303030302e3030302a6b57290d00312d303a36322e372e3028303030302e3030302a6b57290d00312d303a32332e372e3028303030302e3030302a6b564172290d00312d303a34332e372e3028303030302e3030302a6b564172290d00312d303a36332e372e3028303030302e3030302a6b564172290d00312d303a32342e372e3028303030302e3233372a6b564172290d00312d303a34342e372e3028303030302e3134332a6b564172290d00312d303a36342e372e3028303030302e3231362a6b564172290d00312d303a33322e372e30283233362e372a56290d00312d303a35322e372e30283234302e372a56290d00312d303a37322e372e30283234322e302a56290d00312d303a33312e372e30283030332e332a41290d00312d303a35312e372e30283030302e372a41290d00312d303a37312e372e30283030312e332a41290d0021413441320d00
2022-03-25 09:06:40 DEBUG (MainThread) [custom_components.amshan.metercon] Starts with '/', but not a valid P1 message: Data not found.`

**Comment by toreamun** [comment]
Linjer i meldingene skal avsluttes med CR + LF (0x0d + 0x0a). I meldingene i logger er alle LF (0x0a) erstattet med 0x00.

Hex fra loggen - merk at det som skal være er 0d0a er 0d00:
`2f4b414d35 0d00 0d00 302d303a312e302e30283232303332353039303631395729 0d00 312d`

ASCII dekodet (\r\x00 i stedet for \r\n):
`b'/KAM5\r\x00\r\x000-0:1.0.0(220325090619W)\r\x001-'`

Helt på slutten av meldingene er det en checksum. Den stemmer ikke med kalkulert checksum, men hvis jeg bytter ut alle 0d00 med 0d0a blir kalkulert checksum det samme som checksum på slutten av meldingen.

Dette er sansynligvis en bug i enheten som sender data til MQTT topic. Hvilken type enhet benytter du?

**Comment by sesthan** [comment]
> Linjer i meldingene skal avsluttes med CR + LF (0x0d + 0x0a). I meldingene i logger er alle LF (0x0a) erstattet med 0x00.
> 
> Hex fra loggen - merk at det som skal være er 0d0a er 0d00: `2f4b414d35 0d00 0d00 302d303a312e302e30283232303332353039303631395729 0d00 312d`
> 
> ASCII dekodet (\r\x00 i stedet for \r\n): `b'/KAM5\r\x00\r\x000-0:1.0.0(220325090619W)\r\x001-'`
> 
> Helt på slutten av meldingene er det en checksum. Den stemmer ikke med kalkulert checksum, men hvis jeg bytter ut alle 0d00 med 0d0a blir kalkulert checksum det samme som checksum på slutten av meldingen.
> 
> Dette er sansynligvis en bug i enheten som sender data til MQTT topic. Hvilken type enhet benytter du?

Interessant! 
Enheten som kommunicerar med Kamstrup är den här : https://energyintelligence.se/shop/product/p1-till-mqtt-adapter
FW: 3.2_ATOM_20220224-131301

Tror du det är fel på den eller är det från Kamstrup Han modulen ? (https://www.vbenergi.se/elnat/smarta-elmatare/tillgang-till-kundkontakt-aven-kallad-han-port/)

**Comment by toreamun** [comment]
Det er ikke så lett å vite om dette skyldes adapter eller Kamstrup. Men hvis adapter klarer å dekode meldingen og sende ut riktige verdier på andre topic som f.eks /Energy/#, så tyder det på at adapter mottar melding på korrekt format fra Kamstrup, eller har en workaround hvor dem ved dekoding "fikser" melding fra Kamstrup.

**Comment by sesthan** [comment]
Då kanske jag skickar en mail till Energy intelligence och frågor dom. Kan jo henviser till denne tråd eftersom du har redan gjort lite detektivarbete 👍

**Comment by toreamun** [comment]
> Då kanske jag skickar en mail till Energy intelligence och frågor dom. 

Har du fått svar fra Energy intelligence?

**Comment by sesthan** [comment]
> > Då kanske jag skickar en mail till Energy intelligence och frågor dom.
> 
> Har du fått svar fra Energy intelligence?

Ja, fick i måndags. En av utvecklarna har lyckats återskapa och identifiera felet. Dom ska göra en ny FW snart för att fixa det. Så hoppas det blir löst från dom. 

Jag kan återkomma när jag har fått en ny FW installerat och testat.

**Comment by sesthan** [comment]
Jag fick testat en RC idag och fick frem en ny fel. Har skickat info till Energy Intelligence. Men tänkt hålla den här tråd uppdaterat också i fall ni ser något konstigt från amshan. --> 

####

2022-04-08 14:50:02 ERROR (MainThread) [homeassistant.util.logging] Exception in message_received when handling msg on 'esp32_C5170C/raw': 'b'/KAM5\r\n\r\n0-0:1.0.0(220408135001W)\r\n1-0:1.8.0(00060995.412*kWh)\r\n1-0:2.8.0(00000000.000*kWh)\r\n1-0:3.8.0(00000012.696*kVArh)\r\n1-0:4.8.0(00012541.799*kVArh)\r\n1-0:1.7.0(0002.207*kW)\r\n1-0:2.7.0(0000.000*kW)\r\n1-0:3.7.0(0000.000*kVAr)\r\n1-0:4.7.0(0000.503*kVAr)\r\n1-0:21.7.0(0001.948*kW)\r\n1-0:41.7.0(0000.064*kW)\r\n1-0:61.7.0(0000.195*kW)\r\n1-0:22.7.0(0000.000*kW)\r\n1-0:42.7.0(0000.000*kW)\r\n1-0:62.7.0(0000.000*kW)\r\n1-0:23.7.0(0000.000*kVAr)\r\n1-0:43.7.0(0000.000*kVAr)\r\n1-0:63.7.0(0000.000*kVAr)\r\n1-0:24.7.0(0000.202*kVAr)\r\n1-0:44.7.0(0000.095*kVAr)\r\n1-0:64.7.0(0000.206*kVAr)\r\n1-0:32.7.0(234.8*V)\r\n1-0:52.7.0(239.7*V)\r\n1-0:72.7.0(239.3*V)\r\n1-0:31.7.0(008.3*A)\r\n1-0:51.7.0(000.4*A)\r\n1-0:71.7.0(001.4*A)\r\n!7641\r\n''
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/han/dlde.py", line 183, in is_valid
    self._ident = self.identification_line
  File "/usr/local/lib/python3.9/site-packages/han/dlde.py", line 209, in identification_line
    self._ident = Ident(self._readout[: self._data_pos].decode("ascii").strip())
  File "/usr/local/lib/python3.9/site-packages/han/dlde.py", line 112, in __init__
    raise ValueError("Not an Ident message.")
ValueError: Not an Ident message.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/amshan/config_flow.py", line 410, in message_received
    meter_message = get_meter_message(mqtt_message)
  File "/config/custom_components/amshan/metercon.py", line 143, in get_meter_message
    if message.is_valid:
  File "/usr/local/lib/python3.9/site-packages/han/dlde.py", line 185, in is_valid
    _LOGGER.debug("Invalid ident line: %s", self.identification_line)
  File "/usr/local/lib/python3.9/site-packages/han/dlde.py", line 209, in identification_line
    self._ident = Ident(self._readout[: self._data_pos].decode("ascii").strip())
  File "/usr/local/lib/python3.9/site-packages/han/dlde.py", line 112, in __init__
    raise ValueError("Not an Ident message.")
ValueError: Not an Ident message.

2022-04-08 14:50:06 DEBUG (MainThread) [custom_components.amshan.config_flow] Timout waiting 12 seconds for meter measure.
2022-04-08 14:50:12 ERROR (MainThread) [homeassistant.util.logging] Exception in message_received when handling msg on 'esp32_C5170C/raw': 'b'/KAM5\r\n\r\n0-0:1.0.0(220408135011W)\r\n1-0:1.8.0(00060995.418*kWh)\r\n1-0:2.8.0(00000000.000*kWh)\r\n1-0:3.8.0(00000012.696*kVArh)\r\n1-0:4.8.0(00012541.801*kVArh)\r\n1-0:1.7.0(0002.225*kW)\r\n1-0:2.7.0(0000.000*kW)\r\n1-0:3.7.0(0000.000*kVAr)\r\n1-0:4.7.0(0000.507*kVAr)\r\n1-0:21.7.0(0001.946*kW)\r\n1-0:41.7.0(0000.064*kW)\r\n1-0:61.7.0(0000.215*kW)\r\n1-0:22.7.0(0000.000*kW)\r\n1-0:42.7.0(0000.000*kW)\r\n1-0:62.7.0(0000.000*kW)\r\n1-0:23.7.0(0000.000*kVAr)\r\n1-0:43.7.0(0000.000*kVAr)\r\n1-0:63.7.0(0000.000*kVAr)\r\n1-0:24.7.0(0000.202*kVAr)\r\n1-0:44.7.0(0000.095*kVAr)\r\n1-0:64.7.0(0000.210*kVAr)\r\n1-0:32.7.0(234.8*V)\r\n1-0:52.7.0(239.3*V)\r\n1-0:72.7.0(239.2*V)\r\n1-0:31.7.0(008.3*A)\r\n1-0:51.7.0(000.4*A)\r\n1-0:71.7.0(001.5*A)\r\n!225C''
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/han/dlde.py", line 183, in is_valid
    self._ident = self.identification_line
  File "/usr/local/lib/python3.9/site-packages/han/dlde.py", line 209, in identification_line
    self._ident = Ident(self._readout[: self._data_pos].decode("ascii").strip())
  File "/usr/local/lib/python3.9/site-packages/han/dlde.py", line 112, in __init__
    raise ValueError("Not an Ident message.")
ValueError: Not an Ident message.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/amshan/config_flow.py", line 410, in message_received
    meter_message = get_meter_message(mqtt_message)
  File "/config/custom_components/amshan/metercon.py", line 143, in get_meter_message
    if message.is_valid:
  File "/usr/local/lib/python3.9/site-packages/han/dlde.py", line 185, in is_valid
    _LOGGER.debug("Invalid ident line: %s", self.identification_line)
  File "/usr/local/lib/python3.9/site-packages/han/dlde.py", line 209, in identification_line
    self._ident = Ident(self._readout[: self._data_pos].decode("ascii").strip())
  File "/usr/local/lib/python3.9/site-packages/han/dlde.py", line 112, in __init__
    raise ValueError("Not an Ident message.")
ValueError: Not an Ident message.

2022-04-08 14:50:18 DEBUG (MainThread) [custom_components.amshan.config_flow] Timout waiting 12 seconds for meter measure.
2022-04-08 14:50:22 DEBUG (MainThread) [custom_components.amshan.metercon] Got payload without HDLC framing from topic esp32_C5170C/raw: 0d0a2f4b414d350d0a0d0a302d303a312e302e302832323034303831333530323157290d0a312d303a312e382e302830303036303939352e3432342a6b5768290d0a312d303a322e382e302830303030303030302e3030302a6b5768290d0a312d303a332e382e302830303030303031322e3639362a6b56417268290d0a312d303a342e382e302830303031323534312e3830322a6b56417268290d0a312d303a312e372e3028303030322e3230322a6b57290d0a312d303a322e372e3028303030302e3030302a6b57290d0a312d303a332e372e3028303030302e3030302a6b564172290d0a312d303a342e372e3028303030302e3530352a6b564172290d0a312d303a32312e372e3028303030312e3934372a6b57290d0a312d303a34312e372e3028303030302e3036332a6b57290d0a312d303a36312e372e3028303030302e3139322a6b57290d0a312d303a32322e372e3028303030302e3030302a6b57290d0a312d303a34322e372e3028303030302e3030302a6b57290d0a312d303a36322e372e3028303030302e3030302a6b57290d0a312d303a32332e372e3028303030302e3030302a6b564172290d0a312d303a34332e372e3028303030302e3030302a6b564172290d0a312d303a36332e372e3028303030302e3030302a6b564172290d0a312d303a32342e372e3028303030302e3230342a6b564172290d0a312d303a34342e372e3028303030302e3039352a6b564172290d0a312d303a36342e372e3028303030302e3230362a6b564172290d0a312d303a33322e372e30283233352e352a56290d0a312d303a35322e372e30283233392e352a56290d0a312d303a37322e372e30283233392e312a56290d0a312d303a33312e372e30283030382e332a41290d0a312d303a35312e372e30283030302e342a41290d0a312d303a37312e372e30283030312e342a41290d0a21393246350d0a
2022-04-08 14:50:22 DEBUG (MainThread) [custom_components.amshan.metercon] Got payload without HDLC framing from topic esp32_C5170C/raw: 0d0a2f4b414d350d0a0d0a302d303a312e302e302832323034303831333530323157290d0a312d303a312e382e302830303036303939352e3432342a6b5768290d0a312d303a322e382e302830303030303030302e3030302a6b5768290d0a312d303a332e382e302830303030303031322e3639362a6b56417268290d0a312d303a342e382e302830303031323534312e3830322a6b56417268290d0a312d303a312e372e3028303030322e3230322a6b57290d0a312d303a322e372e3028303030302e3030302a6b57290d0a312d303a332e372e3028303030302e3030302a6b564172290d0a312d303a342e372e3028303030302e3530352a6b564172290d0a312d303a32312e372e3028303030312e3934372a6b57290d0a312d303a34312e372e3028303030302e3036332a6b57290d0a312d303a36312e372e3028303030302e3139322a6b57290d0a312d303a32322e372e3028303030302e3030302a6b57290d0a312d303a34322e372e3028303030302e3030302a6b57290d0a312d303a36322e372e3028303030302e3030302a6b57290d0a312d303a32332e372e3028303030302e3030302a6b564172290d0a312d303a34332e372e3028303030302e3030302a6b564172290d0a312d303a36332e372e3028303030302e3030302a6b564172290d0a312d303a32342e372e3028303030302e3230342a6b564172290d0a312d303a34342e372e3028303030302e3039352a6b564172290d0a312d303a36342e372e3028303030302e3230362a6b564172290d0a312d303a33322e372e30283233352e352a56290d0a312d303a35322e372e30283233392e352a56290d0a312d303a37322e372e30283233392e312a56290d0a312d303a33312e372e30283030382e332a41290d0a312d303a35312e372e30283030302e342a41290d0a312d303a37312e372e30283030312e342a41290d0a21393246350d0a

####

**Comment by toreamun** [comment]
Jeg skal se på det.

fre. 8. apr. 2022 kl. 15:13 skrev sesthan ***@***.***>:

**Comment by toreamun** [comment]
https://github.com/toreamun/amshan-homeassistant/releases/tag/2022.4.0

**Comment by toreamun** [comment]
@sesthan Fungerer siste release for deg?

**Comment by sesthan** [comment]
> @sesthan Fungerer siste release for deg?

Installerat igå kväll och ser utt att funka
![image](https://user-images.githubusercontent.com/31334971/164404003-f9dba1d0-74ea-466e-bf10-6418c080950f.png)
![image](https://user-images.githubusercontent.com/31334971/164404097-bca64f29-6f83-4edb-9449-bec26c7331c8.png)
Diagnostics:
[config_entry-amshan-5c9ee64b10dd1efaea5d00c3ebb7b2ad.json.txt](https://github.com/toreamun/amshan-homeassistant/files/8528734/config_entry-amshan-5c9ee64b10dd1efaea5d00c3ebb7b2ad.json.txt)
