### ISSUE TITLE
`Unable to import component: No module named 'han'` i (docker) hass >= 2024.12

### ISSUE THREAD

**Issue by kujeger** [toreamun/amshan-homeassistant#80]
## Version of the custom_component

2023.6

## Configuration

```yaml

Add your logs here.

```

## Describe the bug
Oppgraderte home assistant fra 2024.11 til 2024.12, med offisielle docker image-et.
Etter oppgradering klarer ikke amshan å starte, med denne loggen. Hvis jeg nedgraderer hass til 2024.11, så virker det igjen.

Har prøvd å slå på debug-logs uten at det ga noen flere pekepinner som jeg kunne se; den sier at den laster ned requirements, og jeg ser også at `han` dukker opp i `config/deps/han`.

Jeg ser at docker imaget har gått fra python `3.12.4` til `3.13.0`, kan det være en sammenheng?

## Debug log

```text

2024-12-23 08:35:50.705 ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration 'amshan': Unable to import component: No module named 'han'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1034, in async_get_component
    self._component_future.result()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1014, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self._get_component, True
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1074, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1022, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/amshan/__init__.py", line 11, in <module>
    from han import common as han_type, meter_connection, obis_map
ModuleNotFoundError: No module named 'han'


```

**Comment by kujeger** [comment]
Testet litt videre, kan se ut til at det har vært noen endringer i `han`-pakka? om jeg fjerner `deps` og tvinger hass 2024.11 ti lå laste dem ned på nytt, så klarer ikke amshan å starte der heller.

**Comment by toreamun** [comment]
Nei, det har ikke være noen nylige oppdateringer av amshan. Jeg kommer til å ta en titt på dette nå før nyttår. Det har muligens noe med Python versjon å gjøre.

**Comment by kujeger** [comment]
Oppdaterte hass direkte fra 2024.11 til 2025.3 i dag (og amshan til 2024.12.0), og amshan fungerer, så anser denne som resolved :)
